SAM:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: postgres #172.18.0.2
      port: 5432
      user: airflow
      pass: airflow
      dbname: airflow
      schema: public
  target: dev
